__all__ = ["motd",
           "register",
           "init",
           "daemon",
           "run",
           "publish",
           "build",
           "install",
           "auth",
           "deploy",
           "manage",
           "event",
           "sync",
           "updateui"]
